###hello
GET http://localhost:8000/hello

### user - get 1
GET http://localhost:8000/users/1

### user - add
POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "Sico",
  "email": "abc@gnail.com",
  "mobile" : "010-1332-1231"
}

> {%
client.global.set("newerId", reponse.body.name)%}

### user - get one
GET http://localhost:8000/users/{{newerId}}

### user-update
PATCH http://localhost:8000/users/{{newerId}}
Content-Type:application/json

{
  "name" : "Scio2",
  "email": "adf@gmail.com",
  "mobile": "010-1232-2312"
}

### user - delete
DELETE http://localhost:8000/users/{{newerId}}
